import type { LabCatalogItem, LabSection } from "./types";

export const LAB_CATALOG: LabCatalogItem[] = [
  // =========================
  // BIOCHEMISTRY / XN SINH HÓA
  // =========================
  {
    code: "glucose",
    canonicalCode: "glucose",
    name: "Glucose",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mmol/L",
    displayUnitOptions: ["mmol/L", "mg/dL"],
    referenceRangeText: "3.9 - 5.6 mmol/L",
    isCommon: true,
    sortOrder: 10,
    searchKeywords: ["glucose", "đường huyết", "blood sugar"],
  },
  {
    code: "glucose_mgdl",
    canonicalCode: "glucose",
    name: ". Glucose",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mg/dL",
    displayUnitOptions: ["mg/dL"],
    referenceRangeText: "70 - 101 mg/dL",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 11,
    searchKeywords: ["glucose mg/dl", "đường huyết mg/dl"],
  },
  {
    code: "creatinine",
    canonicalCode: "creatinine",
    name: "Creatinine",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "umol/L",
    displayUnitOptions: ["umol/L", "mg/dL"],
    referenceRangeText: "Nam: 74 - 114; Nữ: 58 - 96 umol/L",
    isCommon: true,
    sortOrder: 20,
    searchKeywords: ["creatinine", "creatinin"],
  },
  {
    code: "creatinine_mgdl",
    canonicalCode: "creatinine",
    name: ". Creatinine",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mg/dL",
    displayUnitOptions: ["mg/dL"],
    referenceRangeText: "Nam: 0.83 - 1.28; Nữ: 0.66 - 1.09 mg/dL",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 21,
    searchKeywords: ["creatinine mg/dl"],
  },
  {
    code: "egfr",
    canonicalCode: "egfr",
    name: ". eGFR (CKD-EPI 2021)",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mL/ph/1.73 m2",
    displayUnitOptions: ["mL/ph/1.73 m2", "mL/min/1.73m2"],
    referenceRangeText: ">= 60 mL/ph/1.73 m2",
    isCommon: true,
    isDerived: true,
    sortOrder: 22,
    searchKeywords: ["egfr", "ckd-epi", "thận"],
  },
  {
    code: "uric_acid",
    canonicalCode: "uric_acid",
    name: "Định lượng Acid Uric",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "umol/L",
    displayUnitOptions: ["umol/L", "mg/dL"],
    referenceRangeText: "Nam: 208 - 428; Nữ: 154 - 357 umol/L",
    isCommon: false,
    sortOrder: 30,
    searchKeywords: ["acid uric", "uric acid", "gout"],
  },
  {
    code: "uric_acid_mgdl",
    canonicalCode: "uric_acid",
    name: ". Uric acid",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mg/dL",
    displayUnitOptions: ["mg/dL"],
    referenceRangeText: "Nam: 3.5 - 7.2; Nữ: 2.6 - 6.0 mg/dL",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 31,
    searchKeywords: ["uric acid mg/dl"],
  },
  {
    code: "cholesterol_total",
    canonicalCode: "cholesterol_total",
    name: "Cholesterol",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mmol/L",
    displayUnitOptions: ["mmol/L", "mg/dL"],
    referenceRangeText: "3.9 - 5.2 mmol/L",
    isCommon: true,
    sortOrder: 40,
    searchKeywords: ["cholesterol toàn phần", "cholesterol total"],
  },
  {
    code: "cholesterol_total_mgdl",
    canonicalCode: "cholesterol_total",
    name: ". Cholesterol",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mg/dL",
    displayUnitOptions: ["mg/dL"],
    referenceRangeText: "150 - 200 mg/dL",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 41,
    searchKeywords: ["cholesterol mg/dl"],
  },
  {
    code: "hdl_c",
    canonicalCode: "hdl_c",
    name: "HDL Cholesterol",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mmol/L",
    displayUnitOptions: ["mmol/L", "mg/dL"],
    referenceRangeText: "> 0.9 mmol/L",
    isCommon: true,
    sortOrder: 50,
    searchKeywords: ["hdl", "hdl-c"],
  },
  {
    code: "hdl_c_mgdl",
    canonicalCode: "hdl_c",
    name: ". HDL Cholesterol",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mg/dL",
    displayUnitOptions: ["mg/dL"],
    referenceRangeText: "> 35 mg/dL",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 51,
    searchKeywords: ["hdl mg/dl"],
  },
  {
    code: "non_hdl_c",
    canonicalCode: "non_hdl_c",
    name: "Non - HDL Cholesterol",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mmol/L",
    displayUnitOptions: ["mmol/L", "mg/dL"],
    referenceRangeText: "",
    isCommon: false,
    sortOrder: 60,
    searchKeywords: ["non hdl", "non-hdl"],
  },
  {
    code: "non_hdl_c_mgdl",
    canonicalCode: "non_hdl_c",
    name: ". Non - HDL Cholesterol",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mg/dL",
    displayUnitOptions: ["mg/dL"],
    referenceRangeText: "",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 61,
    searchKeywords: ["non hdl mg/dl"],
  },
  {
    code: "ldl_c",
    canonicalCode: "ldl_c",
    name: "LDL Cholesterol",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mmol/L",
    displayUnitOptions: ["mmol/L", "mg/dL"],
    referenceRangeText: "< 3.4 mmol/L",
    isCommon: true,
    sortOrder: 70,
    searchKeywords: ["ldl", "ldl-c"],
  },
  {
    code: "ldl_c_mgdl",
    canonicalCode: "ldl_c",
    name: ". LDL Cholesterol",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mg/dL",
    displayUnitOptions: ["mg/dL"],
    referenceRangeText: "< 131 mg/dL",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 71,
    searchKeywords: ["ldl mg/dl"],
  },
  {
    code: "triglyceride",
    canonicalCode: "triglyceride",
    name: "Triglyceride",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mmol/L",
    displayUnitOptions: ["mmol/L", "mg/dL"],
    referenceRangeText: "0.46 - 1.88 mmol/L",
    isCommon: true,
    sortOrder: 80,
    searchKeywords: ["triglyceride", "tg"],
  },
  {
    code: "triglyceride_mgdl",
    canonicalCode: "triglyceride",
    name: ". Triglyceride",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mg/dL",
    displayUnitOptions: ["mg/dL"],
    referenceRangeText: "40 - 166 mg/dL",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 81,
    searchKeywords: ["triglyceride mg/dl"],
  },
  {
    code: "ast",
    canonicalCode: "ast",
    name: "Đo hoạt độ AST (Aspartat Aminotransferase)",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "U/L",
    displayUnitOptions: ["U/L"],
    referenceRangeText: "Nam < 40 U/L; Nữ < 31 U/L",
    isCommon: true,
    sortOrder: 90,
    searchKeywords: ["ast", "sgot"],
  },
  {
    code: "alt",
    canonicalCode: "alt",
    name: "Đo hoạt độ ALT (Alanin Aminotransferase)",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "U/L",
    displayUnitOptions: ["U/L"],
    referenceRangeText: "Nam < 41 U/L; Nữ < 31 U/L",
    isCommon: true,
    sortOrder: 91,
    searchKeywords: ["alt", "sgpt"],
  },
  {
    code: "ggt",
    canonicalCode: "ggt",
    name: "Đo hoạt độ GGT",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "U/L",
    displayUnitOptions: ["U/L"],
    referenceRangeText: "< 40 U/L",
    isCommon: false,
    sortOrder: 92,
    searchKeywords: ["ggt"],
  },
  {
    code: "sodium",
    canonicalCode: "sodium",
    name: "Natri",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mmol/L",
    displayUnitOptions: ["mmol/L"],
    referenceRangeText: "136 - 146 mmol/L",
    isCommon: true,
    sortOrder: 100,
    searchKeywords: ["natri", "sodium", "na"],
  },
  {
    code: "potassium",
    canonicalCode: "potassium",
    name: "Kali",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mmol/L",
    displayUnitOptions: ["mmol/L"],
    referenceRangeText: "3.4 - 5.1 mmol/L",
    isCommon: true,
    sortOrder: 101,
    searchKeywords: ["kali", "potassium", "k"],
  },
  {
    code: "chloride",
    canonicalCode: "chloride",
    name: "Định lượng Clo",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mmol/L",
    displayUnitOptions: ["mmol/L"],
    referenceRangeText: "98 - 109 mmol/L",
    isCommon: false,
    sortOrder: 102,
    searchKeywords: ["clo", "chloride", "cl"],
  },
  {
    code: "calcium_total",
    canonicalCode: "calcium_total",
    name: "Định lượng Canxi toàn phần [Máu]",
    section: "biochemistry",
    groupName: "XN SINH HÓA",
    valueType: "numeric",
    canonicalUnit: "mmol/L",
    displayUnitOptions: ["mmol/L"],
    referenceRangeText: "2.10 - 2.55 mmol/L",
    isCommon: false,
    sortOrder: 103,
    searchKeywords: ["canxi", "calcium"],
  },

  // =========================
  // HAEMATOLOGY / XN HUYẾT HỌC
  // =========================
  {
    code: "cbc_panel",
    canonicalCode: "cbc_panel",
    name: "Tổng phân tích tế bào máu bằng máy đếm laser (CBC)",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "text",
    canonicalUnit: "",
    referenceRangeText: "",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 200,
    searchKeywords: ["cbc", "công thức máu"],
  },
  {
    code: "wbc",
    canonicalCode: "wbc",
    name: "WBC",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "10^9/L",
    displayUnitOptions: ["10^9/L", "G/L"],
    referenceRangeText: "4 - 10 G/L",
    isCommon: true,
    sortOrder: 201,
    searchKeywords: ["wbc", "bạch cầu"],
  },
  {
    code: "neu_percent",
    canonicalCode: "neu_percent",
    name: "- NEU %",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "% N",
    displayUnitOptions: ["% N", "%"],
    referenceRangeText: "45 - 75% N",
    isCommon: false,
    sortOrder: 202,
    searchKeywords: ["neu %", "neutrophil %"],
  },
  {
    code: "neu_abs",
    canonicalCode: "neu_abs",
    name: "- NEU #",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "N",
    displayUnitOptions: ["N"],
    referenceRangeText: "1.8 - 7.5 N",
    isCommon: false,
    sortOrder: 203,
    searchKeywords: ["neu #", "neutrophil abs"],
  },
  {
    code: "lym_percent",
    canonicalCode: "lym_percent",
    name: "- LYM %",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "% L",
    displayUnitOptions: ["% L", "%"],
    referenceRangeText: "20 - 35% L",
    isCommon: false,
    sortOrder: 204,
    searchKeywords: ["lym %", "lymphocyte %"],
  },
  {
    code: "lym_abs",
    canonicalCode: "lym_abs",
    name: "- LYM #",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "L",
    displayUnitOptions: ["L"],
    referenceRangeText: "0.8 - 3.5 L",
    isCommon: false,
    sortOrder: 205,
    searchKeywords: ["lym #", "lymphocyte abs"],
  },
  {
    code: "mono_percent",
    canonicalCode: "mono_percent",
    name: "- MONO %",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "% M",
    displayUnitOptions: ["% M", "%"],
    referenceRangeText: "4 - 10% M",
    isCommon: false,
    sortOrder: 206,
    searchKeywords: ["mono %", "monocyte %"],
  },
  {
    code: "mono_abs",
    canonicalCode: "mono_abs",
    name: "- MONO #",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "M",
    displayUnitOptions: ["M"],
    referenceRangeText: "0.16 - 1.0 M",
    isCommon: false,
    sortOrder: 207,
    searchKeywords: ["mono #", "monocyte abs"],
  },
  {
    code: "eos_percent",
    canonicalCode: "eos_percent",
    name: "- EOS %",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "% E",
    displayUnitOptions: ["% E", "%"],
    referenceRangeText: "1 - 8% E",
    isCommon: false,
    sortOrder: 208,
    searchKeywords: ["eos %", "eosinophil %"],
  },
  {
    code: "eos_abs",
    canonicalCode: "eos_abs",
    name: "- EOS #",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "E",
    displayUnitOptions: ["E"],
    referenceRangeText: "0.01 - 0.8 E",
    isCommon: false,
    sortOrder: 209,
    searchKeywords: ["eos #", "eosinophil abs"],
  },
  {
    code: "baso_percent",
    canonicalCode: "baso_percent",
    name: "- BASO %",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "% B",
    displayUnitOptions: ["% B", "%"],
    referenceRangeText: "0 - 2% B",
    isCommon: false,
    sortOrder: 210,
    searchKeywords: ["baso %", "basophil %"],
  },
  {
    code: "baso_abs",
    canonicalCode: "baso_abs",
    name: "- BASO #",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "B",
    displayUnitOptions: ["B"],
    referenceRangeText: "0 - 0.2 B",
    isCommon: false,
    sortOrder: 211,
    searchKeywords: ["baso #", "basophil abs"],
  },
  {
    code: "luc_percent",
    canonicalCode: "luc_percent",
    name: "- LUC%",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "%",
    referenceRangeText: "",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 212,
    searchKeywords: ["luc%"],
  },
  {
    code: "luc_abs",
    canonicalCode: "luc_abs",
    name: "- LUC#",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "",
    referenceRangeText: "",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 213,
    searchKeywords: ["luc#"],
  },
  {
    code: "ig_percent",
    canonicalCode: "ig_percent",
    name: "- IG%",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "%",
    displayUnitOptions: ["%"],
    referenceRangeText: "0.16 - 0.61 %",
    isCommon: false,
    sortOrder: 214,
    searchKeywords: ["ig%", "immature granulocyte"],
  },
  {
    code: "rbc",
    canonicalCode: "rbc",
    name: "RBC",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "10^12/L",
    displayUnitOptions: ["10^12/L", "T/L"],
    referenceRangeText: "3.8 - 5.5 T/L",
    isCommon: true,
    sortOrder: 220,
    searchKeywords: ["rbc", "hồng cầu"],
  },
  {
    code: "hemoglobin",
    canonicalCode: "hemoglobin",
    name: ". Hb",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "g/L",
    displayUnitOptions: ["g/L"],
    referenceRangeText: "120 - 175 g/L",
    isCommon: true,
    sortOrder: 221,
    searchKeywords: ["hb", "hemoglobin", "huyết sắc tố"],
  },
  {
    code: "hematocrit",
    canonicalCode: "hematocrit",
    name: ". HCT",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "L/L",
    displayUnitOptions: ["L/L", "%"],
    referenceRangeText: "0.35 - 0.53 L/L",
    isCommon: true,
    sortOrder: 222,
    searchKeywords: ["hct", "hematocrit"],
  },
  {
    code: "mcv",
    canonicalCode: "mcv",
    name: ". MCV",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "fL",
    displayUnitOptions: ["fL"],
    referenceRangeText: "78 - 100 fL",
    isCommon: true,
    sortOrder: 223,
    searchKeywords: ["mcv"],
  },
  {
    code: "mch",
    canonicalCode: "mch",
    name: ". MCH",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "pG",
    displayUnitOptions: ["pG", "pg"],
    referenceRangeText: "26.7 - 30.7 pG",
    isCommon: true,
    sortOrder: 224,
    searchKeywords: ["mch"],
  },
  {
    code: "mchc",
    canonicalCode: "mchc",
    name: ". MCHC",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "g/L",
    displayUnitOptions: ["g/L"],
    referenceRangeText: "320 - 350 g/L",
    isCommon: true,
    sortOrder: 225,
    searchKeywords: ["mchc"],
  },
  {
    code: "chcm",
    canonicalCode: "chcm",
    name: ". CHCM",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "",
    referenceRangeText: "",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 226,
    searchKeywords: ["chcm"],
  },
  {
    code: "rdw",
    canonicalCode: "rdw",
    name: ". RDW",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "%",
    displayUnitOptions: ["%"],
    referenceRangeText: "12 - 20 %",
    isCommon: false,
    sortOrder: 227,
    searchKeywords: ["rdw"],
  },
  {
    code: "hdw",
    canonicalCode: "hdw",
    name: ". HDW",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "",
    referenceRangeText: "",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 228,
    searchKeywords: ["hdw"],
  },
  {
    code: "ch",
    canonicalCode: "ch",
    name: ". CH",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "",
    referenceRangeText: "",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 229,
    searchKeywords: ["ch"],
  },
  {
    code: "mdw",
    canonicalCode: "mdw",
    name: ". MDW",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "",
    referenceRangeText: "",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 230,
    searchKeywords: ["mdw"],
  },
  {
    code: "nrbc_percent",
    canonicalCode: "nrbc_percent",
    name: ". NRBC %",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "%",
    displayUnitOptions: ["%"],
    referenceRangeText: "0.0 - 2.0 %",
    isCommon: false,
    sortOrder: 231,
    searchKeywords: ["nrbc %"],
  },
  {
    code: "nrbc_abs",
    canonicalCode: "nrbc_abs",
    name: ". NRBC#",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "10^9/L",
    displayUnitOptions: ["10^9/L", "G/L"],
    referenceRangeText: "0.0 - 2.0 G/L",
    isCommon: false,
    sortOrder: 232,
    searchKeywords: ["nrbc#", "nrbc abs"],
  },
  {
    code: "platelet",
    canonicalCode: "platelet",
    name: "PLT",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "10^9/L",
    displayUnitOptions: ["10^9/L", "G/L"],
    referenceRangeText: "150 - 450 G/L",
    isCommon: true,
    sortOrder: 233,
    searchKeywords: ["plt", "platelet", "tiểu cầu"],
  },
  {
    code: "mpv",
    canonicalCode: "mpv",
    name: "MPV",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "fL",
    displayUnitOptions: ["fL"],
    referenceRangeText: "7 - 12 fL",
    isCommon: false,
    sortOrder: 234,
    searchKeywords: ["mpv"],
  },
  {
    code: "pdw",
    canonicalCode: "pdw",
    name: "PDW",
    section: "hematology",
    groupName: "XN HUYẾT HỌC",
    valueType: "numeric",
    canonicalUnit: "",
    referenceRangeText: "",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 235,
    searchKeywords: ["pdw"],
  },

  // =========================
  // IMMUNOLOGY / XN MIỄN DỊCH
  // =========================
  {
    code: "hbsag",
    canonicalCode: "hbsag",
    name: "HBsAg miễn dịch tự động",
    section: "immunology",
    groupName: "XN MIỄN DỊCH",
    valueType: "text",
    canonicalUnit: "IU/mL",
    displayUnitOptions: ["IU/mL"],
    referenceRangeText: "<0.03 IU/mL: Âm tính, >=0.03 IU/mL: Dương tính",
    isCommon: false,
    sortOrder: 300,
    searchKeywords: ["hbsag", "viêm gan b"],
  },
  {
    code: "anti_hbs",
    canonicalCode: "anti_hbs",
    name: "HbsAb định lượng (Anti Hbs)",
    section: "immunology",
    groupName: "XN MIỄN DỊCH",
    valueType: "numeric",
    canonicalUnit: "IU/L",
    displayUnitOptions: ["IU/L", "mIU/mL"],
    referenceRangeText: ">=10 IU/L",
    isCommon: false,
    sortOrder: 301,
    searchKeywords: ["anti hbs", "hbsab"],
  },
  {
    code: "hcv_ab",
    canonicalCode: "hcv_ab",
    name: "HCV Ab miễn dịch tự động",
    section: "immunology",
    groupName: "XN MIỄN DỊCH",
    valueType: "text",
    canonicalUnit: "S/CO",
    displayUnitOptions: ["S/CO"],
    referenceRangeText: "S/CO <1",
    isCommon: false,
    sortOrder: 302,
    searchKeywords: ["hcv ab", "viêm gan c"],
  },
  {
    code: "ferritin",
    canonicalCode: "ferritin",
    name: "Định lượng Ferritin",
    section: "immunology",
    groupName: "XN MIỄN DỊCH",
    valueType: "numeric",
    canonicalUnit: "ng/mL",
    displayUnitOptions: ["ng/mL"],
    referenceRangeText: "Nam: 30-400 ng/mL, Nữ: 15-150 ng/mL",
    isCommon: false,
    sortOrder: 303,
    searchKeywords: ["ferritin"],
  },
  {
    code: "tsh",
    canonicalCode: "tsh",
    name: "Định lượng TSH (Thyroid Stimulating hormone)",
    section: "immunology",
    groupName: "XN MIỄN DỊCH",
    valueType: "numeric",
    canonicalUnit: "mIU/L",
    displayUnitOptions: ["mIU/L", "uIU/mL"],
    referenceRangeText: "0.34 - 4.22 mIU/L",
    isCommon: true,
    sortOrder: 304,
    searchKeywords: ["tsh", "tuyến giáp"],
  },
  {
    code: "ft4",
    canonicalCode: "ft4",
    name: "Định lượng FT4 (Free Thyroxine)",
    section: "immunology",
    groupName: "XN MIỄN DỊCH",
    valueType: "numeric",
    canonicalUnit: "pmol/L",
    displayUnitOptions: ["pmol/L"],
    referenceRangeText: "9.93 - 20.51 pmol/L",
    isCommon: true,
    sortOrder: 305,
    searchKeywords: ["ft4", "free thyroxine"],
  },

  // =========================
  // URINALYSIS / XN SH NƯỚC TIỂU
  // =========================
  {
    code: "urine_10_panel",
    canonicalCode: "urine_10_panel",
    name: "Nước tiểu 10 thông số (máy)",
    section: "urinalysis",
    groupName: "XN SH NƯỚC TIỂU",
    valueType: "text",
    canonicalUnit: "",
    referenceRangeText: "",
    isCommon: false,
    isAdvanced: true,
    sortOrder: 400,
    searchKeywords: ["nước tiểu 10 thông số"],
  },
  {
    code: "urine_color",
    canonicalCode: "urine_color",
    name: ". . COLOR",
    section: "urinalysis",
    groupName: "XN SH NƯỚC TIỂU",
    valueType: "text",
    canonicalUnit: "",
    referenceRangeText: "Vàng nhạt",
    isCommon: true,
    sortOrder: 401,
    searchKeywords: ["color", "màu nước tiểu"],
  },
  {
    code: "urine_clarity",
    canonicalCode: "urine_clarity",
    name: ". . CLARITY",
    section: "urinalysis",
    groupName: "XN SH NƯỚC TIỂU",
    valueType: "text",
    canonicalUnit: "",
    referenceRangeText: "(Trong)",
    isCommon: true,
    sortOrder: 402,
    searchKeywords: ["clarity", "độ trong"],
  },
  {
    code: "urine_glu",
    canonicalCode: "urine_glu",
    name: ". . GLU",
    section: "urinalysis",
    groupName: "XN SH NƯỚC TIỂU",
    valueType: "text",
    canonicalUnit: "mmol/L",
    displayUnitOptions: ["mmol/L"],
    referenceRangeText: "Bình thường: <1.7 mmol/L",
    isCommon: true,
    sortOrder: 403,
    searchKeywords: ["glu niệu", "urine glucose"],
  },
  {
    code: "urine_bil",
    canonicalCode: "urine_bil",
    name: ". . BIL",
    section: "urinalysis",
    groupName: "XN SH NƯỚC TIỂU",
    valueType: "text",
    canonicalUnit: "umol/L",
    displayUnitOptions: ["umol/L"],
    referenceRangeText: "Âm tính: <3.4 umol/L",
    isCommon: false,
    sortOrder: 404,
    searchKeywords: ["bil niệu", "bilirubin niệu"],
  },
  {
    code: "urine_ket",
    canonicalCode: "urine_ket",
    name: ". . KET",
    section: "urinalysis",
    groupName: "XN SH NƯỚC TIỂU",
    valueType: "text",
    canonicalUnit: "mmol/L",
    displayUnitOptions: ["mmol/L"],
    referenceRangeText: "Âm tính: <0.5 mmol/L",
    isCommon: true,
    sortOrder: 405,
    searchKeywords: ["ket niệu", "ketone niệu"],
  },
  {
    code: "urine_sg",
    canonicalCode: "urine_sg",
    name: ". . SG",
    section: "urinalysis",
    groupName: "XN SH NƯỚC TIỂU",
    valueType: "numeric",
    canonicalUnit: "",
    referenceRangeText: "1.01 - 1.025",
    isCommon: false,
    sortOrder: 406,
    searchKeywords: ["specific gravity", "sg"],
  },
  {
    code: "urine_ph",
    canonicalCode: "urine_ph",
    name: ". . pH",
    section: "urinalysis",
    groupName: "XN SH NƯỚC TIỂU",
    valueType: "numeric",
    canonicalUnit: "",
    referenceRangeText: "4.8 - 7.5",
    isCommon: true,
    sortOrder: 407,
    searchKeywords: ["ph niệu", "urine ph"],
  },
  {
    code: "urine_alb_cre",
    canonicalCode: "urine_alb_cre",
    name: ". . . Alb/Cre (bán định lượng)",
    section: "urinalysis",
    groupName: "XN SH NƯỚC TIỂU",
    valueType: "numeric",
    canonicalUnit: "mg/mmoL",
    displayUnitOptions: ["mg/mmoL", "mg/mmol"],
    referenceRangeText: "<3.4 mg/mmoL",
    isCommon: false,
    sortOrder: 408,
    searchKeywords: ["alb/cre", "albumin creatinine"],
  },
  {
    code: "urine_pro",
    canonicalCode: "urine_pro",
    name: ". . PRO",
    section: "urinalysis",
    groupName: "XN SH NƯỚC TIỂU",
    valueType: "text",
    canonicalUnit: "g/L",
    displayUnitOptions: ["g/L"],
    referenceRangeText: "Âm tính: <0.1 g/L",
    isCommon: true,
    sortOrder: 409,
    searchKeywords: ["protein niệu", "pro niệu"],
  },
  {
    code: "urine_uro",
    canonicalCode: "urine_uro",
    name: ". . URO",
    section: "urinalysis",
    groupName: "XN SH NƯỚC TIỂU",
    valueType: "numeric",
    canonicalUnit: "umol/L",
    displayUnitOptions: ["umol/L"],
    referenceRangeText: "Bình thường: <17 umol/L",
    isCommon: false,
    sortOrder: 410,
    searchKeywords: ["uro", "urobilinogen"],
  },
  {
    code: "urine_nit",
    canonicalCode: "urine_nit",
    name: ". . NIT",
    section: "urinalysis",
    groupName: "XN SH NƯỚC TIỂU",
    valueType: "text",
    canonicalUnit: "",
    referenceRangeText: "Âm tính",
    isCommon: true,
    sortOrder: 411,
    searchKeywords: ["nit niệu", "nitrite"],
  },
  {
    code: "urine_leu",
    canonicalCode: "urine_leu",
    name: ". . LEU",
    section: "urinalysis",
    groupName: "XN SH NƯỚC TIỂU",
    valueType: "text",
    canonicalUnit: "uL",
    displayUnitOptions: ["uL", "/uL"],
    referenceRangeText: "Âm tính: <10 /uL",
    isCommon: true,
    sortOrder: 412,
    searchKeywords: ["leu niệu", "leukocyte"],
  },
  {
    code: "urine_blood",
    canonicalCode: "urine_blood",
    name: ". . BLOOD",
    section: "urinalysis",
    groupName: "XN SH NƯỚC TIỂU",
    valueType: "text",
    canonicalUnit: "Ery/uL",
    displayUnitOptions: ["Ery/uL"],
    referenceRangeText: "Âm tính: <5 Ery/uL",
    isCommon: true,
    sortOrder: 413,
    searchKeywords: ["blood niệu", "hồng cầu niệu"],
  },
];

export const COMMON_LAB_CODES = LAB_CATALOG.filter((item) => item.isCommon).map(
  (item) => item.code
);

export const LAB_SECTIONS: Array<{ key: LabSection; label: string; labelEn?: string }> = [
  { key: "biochemistry", label: "XN SINH HÓA", labelEn: "BIOCHEMISTRY" },
  { key: "hematology", label: "XN HUYẾT HỌC", labelEn: "HAEMATOLOGY" },
  { key: "immunology", label: "XN MIỄN DỊCH", labelEn: "IMMUNOLOGY" },
  { key: "urinalysis", label: "XN SH NƯỚC TIỂU", labelEn: "URINALYSIS" },
  { key: "other", label: "XÉT NGHIỆM KHÁC", labelEn: "OTHER" },
];

export function findLabCatalogItem(code: string) {
  return LAB_CATALOG.find((item) => item.code === code);
}

export function groupLabsBySection(items: LabCatalogItem[]) {
  return items.reduce<Record<string, LabCatalogItem[]>>((acc, item) => {
    if (!acc[item.section]) acc[item.section] = [];
    acc[item.section].push(item);
    return acc;
  }, {});
}